version: "3.9"

services:
  postgres:
    image: postgres:17

    container_name: medicare-postgres

    restart: unless-stopped

    environment:
      POSTGRES_USER: postgres

      POSTGRES_PASSWORD: 1@Imunique

      POSTGRES_DB: mediCare

    ports:
      - "5433:5432"

    volumes:
      - postgres_data:/var/lib/postgresql/data

  backend:
    build:
      context: ./integration

    container_name: medicare-backend

    depends_on:
      - postgres

    env_file:
      - ./integration/.env.docker

    ports:
      - "3000:3000"

  nginx:
    build:
      context: .

      dockerfile: nginx/Dockerfile

    container_name: medicare-nginx

    depends_on:
      - backend

    ports:
      - "80:80"

volumes:
  postgres_data:
