export { Section } from "./Section";
export { Header } from "./Header";
// export { Footer } from "./Footer";
export { Carousel } from "./carousel/ReactCarousel";
export { SearchBySpeciality } from "./search-by-speciality/SearchBySpeciality";
export { Button } from "./button/Button";
export { SideBar } from "./SideBar";
export { Login } from "./login/Login";
export { SignUp } from "./login/Signup";
export { ForgotPassword } from "./login/ForgotPassword";
export { TextField } from "./text-field/TextField";
export { MyAccount } from "./my-account/MyAccount";
export { AuthProvider } from "./AuthProvider";
export { Loader } from "./Loader";
export { ProtectedRoute } from "./ProtectedRoute";
export { AdminSideBar } from "./admin/AdminSideBar";
export { DataTable } from "./Table";
